import { test, expect } from '@playwright/test';

test('full journey: auth, manual route, share, offline edit and sync', async ({ page, browser, context }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'Впервые здесь? Создать аккаунт' }).click();
  await page.getByLabel('Email', { exact: true }).fill(`e2e-${Date.now()}@example.com`);
  await page.getByLabel('Пароль · от 10 символов').fill('e2e-safe-password');
  await page.getByRole('button', { name: 'Создать аккаунт', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Мои поездки.' })).toBeVisible();
  await page.getByRole('button', { name: 'Новая поездка', exact: true }).click();
  await page.getByLabel('Название поездки').fill('Москва → Тверь');
  await page.getByLabel('Откуда', { exact: true }).fill('Москва');
  await page.getByLabel('Куда', { exact: true }).fill('Тверь');
  await page.getByRole('button', { name: 'Создать маршрут' }).click();
  await expect(page.getByRole('heading', { name: 'Москва → Тверь' })).toBeVisible();
  await page.getByRole('button', { name: 'Добавить точку' }).click();
  await page.getByLabel('Название', { exact: true }).fill('Кофе у озера');
  await page.getByLabel('Тип остановки').selectOption('FOOD');
  await page.getByLabel('Остановка, минут').fill('20');
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Кофе у озера' })).toBeVisible();
  await page.getByRole('button', { name: 'Изменить участок Москва — Кофе у озера', exact: true }).click();
  await page.getByLabel('Расстояние, км').fill('100');
  await page.getByLabel('Время в пути, минут').fill('90');
  await page.getByLabel('Ссылка на навигацию').fill('https://yandex.ru/maps/?rtext=55.75,37.61~56.85,35.91');
  await page.getByLabel('Заметки об участке').fill('Проверить дорогу');
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Навигация · Yandex' })).toHaveAttribute('href', 'https://yandex.ru/maps/?rtext=55.75,37.61~56.85,35.91');
  await expect(page.locator('.stats')).toContainText('1 ч 50 мин');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'JSON', exact: true }).click();
  const download = await downloadPromise; expect(download.suggestedFilename()).toContain('.json');
  await expect(page.locator('.sync-status')).toContainText('Изменения сохранены');
  await page.getByRole('button', { name: 'Поделиться', exact: true }).click();
  await page.getByRole('button', { name: 'Создать ссылку', exact: true }).click();
  const url = await page.getByLabel('Живая ссылка').inputValue();
  const guest = await browser.newContext(); const guestPage = await guest.newPage();
  await guestPage.goto(url);
  await expect(guestPage.getByRole('heading', { name: 'Москва → Тверь' })).toBeVisible();
  await expect(guestPage.getByRole('button', { name: 'Добавить точку' })).toHaveCount(0);
  await expect(guestPage.getByRole('link', { name: 'Навигация · Yandex' })).toBeVisible();
  await page.getByRole('button', { name: 'Закрыть', exact: true }).click();
  await page.evaluate(async () => { await navigator.serviceWorker.ready; });
  await context.setOffline(true);
  await page.getByRole('button', { name: 'Редактировать заметки поездки' }).click();
  await page.getByLabel('Заметки к поездке', { exact: true }).fill('Офлайн: взять термос');
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(page.locator('.sync-status')).toContainText('Сохранено на устройстве');
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Мои поездки.' })).toBeVisible();
  await page.getByRole('button', { name: 'Москва → Тверь', exact: true }).click();
  await expect(page.getByText('Офлайн: взять термос', { exact: true })).toBeVisible();
  await context.setOffline(false);
  await expect(page.locator('.sync-status')).toContainText('Изменения сохранены');
  await guestPage.reload();
  await expect(guestPage.getByText('Офлайн: взять термос', { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect(page.getByRole('button', { name: 'Добавить точку' })).toBeVisible();
  await guest.close();
  expect(errors).toEqual([]);
});
